package org.owntracks.android.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "WAYPOINT_IN".
 */
public class WaypointIn {

    private Long id;
    /** Not-null value. */
    private String topic;
    /** Not-null value. */
    private String description;
    private double geofenceLatitude;
    private double geofenceLongitude;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public WaypointIn() {
    }

    public WaypointIn(Long id) {
        this.id = id;
    }

    public WaypointIn(Long id, String topic, String description, double geofenceLatitude, double geofenceLongitude) {
        this.id = id;
        this.topic = topic;
        this.description = description;
        this.geofenceLatitude = geofenceLatitude;
        this.geofenceLongitude = geofenceLongitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTopic() {
        return topic;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTopic(String topic) {
        this.topic = topic;
    }

    /** Not-null value. */
    public String getDescription() {
        return description;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescription(String description) {
        this.description = description;
    }

    public double getGeofenceLatitude() {
        return geofenceLatitude;
    }

    public void setGeofenceLatitude(double geofenceLatitude) {
        this.geofenceLatitude = geofenceLatitude;
    }

    public double getGeofenceLongitude() {
        return geofenceLongitude;
    }

    public void setGeofenceLongitude(double geofenceLongitude) {
        this.geofenceLongitude = geofenceLongitude;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
